default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  pool: <%= ENV.fetch("DATABASE_POOL", ENV.fetch("RAILS_MAX_THREADS", 5)) %>

development:
  <<: *default
  database: youtube_app_development

test:
  <<: *default
  database: youtube_app_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "youtube_app_production") %>

  queue:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "youtube_app_production") %>

  cache:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "youtube_app_production") %>

  cable:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "youtube_app_production") %>
